### ISSUE TITLE
When clauses are not working

### ISSUE THREAD

**Issue by juliandecoss** [Joffref/cedar#16]
Joffref one question, is it allow to use un when {} clauses here? because i have the following policy:

permit(
    principal in Role::"admin",
    action == Action::"create",
    resource
)
when {
    resource.id like "/inventory*"
};
i already review everything but the policy is answering Deny, however i tried the same policy with the same data in [Cedar Playground](https://www.cedarpolicy.com/en/playground) and responds allow, do you know why?

**Comment by Joffref** [comment]
Hey @juliandecoss, thanks for opening this issue. I'll get a closer look to that soon.

Do you have any relevant traces or code to share. In order to reproduce the bug 😄

**Comment by juliandecoss** [comment]
@Joffref  thanks for your answer, i was taking a closer look it turns out, in my JSON entity was having an extra "}" and that was affecting the result returning Deny, but because it didnt crashed i though it was something different, Thank you so much for your answer i will close this issue!

**Comment by Joffref** [comment]
As a follow of your issue, did you expect on a not serializable policy to have an error. Or do you think this behavior is normal and validation should be handled by another method?
